//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.11.16 at 02:15:21 PM CST 
//


package ncsa.d2k.modules.core.io.proxy;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ncsa.d2k.modules.core.io.proxy package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DataObjectCacheInfo_QNAME = new QName("", "dataObjectCacheInfo");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ncsa.d2k.modules.core.io.proxy
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataObjectCacheRecord }
     * 
     */
    public DataObjectCacheRecord createDataObjectCacheRecord() {
        return new DataObjectCacheRecord();
    }

    /**
     * Create an instance of {@link DataObjectCacheRecords }
     * 
     */
    public DataObjectCacheRecords createDataObjectCacheRecords() {
        return new DataObjectCacheRecords();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataObjectCacheRecords }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dataObjectCacheInfo")
    public JAXBElement<DataObjectCacheRecords> createDataObjectCacheInfo(DataObjectCacheRecords value) {
        return new JAXBElement<DataObjectCacheRecords>(_DataObjectCacheInfo_QNAME, DataObjectCacheRecords.class, null, value);
    }

}
