package ncsa.d2k.modules.core.io.sql;

/**
 * <p>Title: AssoRuleReport </p>
 * <p>Description: Extract association rules from a cube table generated by ArrayCube algorithm </p>
 * <p>Copyright: Copyright (c) 2002</p>
 * <p>Company: NCSA ALG </p>
 * @author Dora Cai
 * @version 1.0
 */


import ncsa.d2k.core.*;
import ncsa.d2k.core.modules.*;
import ncsa.d2k.core.modules.UserView;
import ncsa.d2k.userviews.swing.*;
import ncsa.d2k.modules.core.datatype.table.basic.*;
import ncsa.gui.Constrain;
import ncsa.gui.JOutlinePanel;
import java.sql.*;
import java.util.*;
import java.util.ArrayList;
import java.text.*;
import javax.swing.table.*;
import javax.swing.*;
import java.io.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.table.TableColumnModel;
import javax.swing.JTable;
import oracle.sql.*;
import oracle.jdbc.driver.*;

public class RuleAsscReport extends UIModule
        {
  JOptionPane msgBoard = new JOptionPane();
  File file;
  FileWriter fw;
  ConnectionWrapper cw;
  Connection con;
  String cubeTableName;
  double minSupport = 0.1;
  double minConfidence = 0.5;
  int colCnt;
  int totalRow;
  static String NOTHING = "";
  static String DELIMITER = "\t";
  static String ELN = "\n";
  static String NA = "NOAVL";
  // TableImpl object to keep rules. The table has 4 columns: head, body, support and confidence
  TableImpl ruleTable;
  // ArrayList to keep rules represented by item-indexes
  // (the indexes map to the array index of "itemLabels").
  // The items except the last 3 are left handside rules
  // Array to keep all rules
  // ArrayList finalRules;
  // ArrayList to keep all rule labels
  ArrayList itemLabels;

  String [] columnHeading;
  GenericTableModel ruleModel;
  JTable ruleList;
  JButton doneBtn;
  JButton printBtn;

  public RuleAsscReport() {
  }

  public String getInputInfo (int i) {
		switch (i) {
			case 0: return "Each rule consists of a list of distinct rule ids followed by a confidence and a support value. ";
			case 1: return "An array that contains all rule labels (column name = column value).";
			default: return "No such input";
		}
	}

  public String getOutputInfo (int i) {
		switch (i) {
			default: return "No such output";
		}
	}

  public String getModuleInfo () {
		return "<html>  <head>      </head>  <body>    Display the association rules in text format.  </body></html>";
	}

  public String[] getOutputTypes () {
		String[] types = {		};
		return types;
	}

  public String[] getInputTypes () {
		String[] types = {"ncsa.d2k.modules.core.datatype.table.basic.TableImpl","java.util.ArrayList"};
		return types;
	}

  protected String[] getFieldNameMapping () {
    return null;
  }

    /**
    Create the UserView object for this module-view combination.
    @return The UserView associated with this module.
  */
  protected UserView createUserView() {
    return new DisplayRuleView();
  }

  public class DisplayRuleView extends JUserInputPane
    implements ActionListener {

    public void setInput(Object input, int index) {
      closeIt();
      removeAll();

      if (index == 0) {
        ruleTable = new TableImpl();
        ruleTable = (TableImpl)input;
      }
      else if (index == 1) {
        itemLabels = new ArrayList();
        itemLabels = (ArrayList)input;
        doGUI();
        displayRules();
      }
    }

    public Dimension getPreferredSize() {
      return new Dimension (500, 450);
    }

    public void initView(ViewModule mod) {
      removeAll();
      ruleTable = new TableImpl();
      ruleTable = (TableImpl)pullInput(0);
      itemLabels = new ArrayList();
      itemLabels = (ArrayList)pullInput(1);
      doGUI();
      displayRules();
    }

    public void doGUI() {
      // Panel to hold outline panels
      JPanel displayRulePanel = new JPanel();
      displayRulePanel.setLayout (new GridBagLayout());

      // Outline panel for rules
      String[] columnHeading = {"IF","-->","THEN","S","C"};
      JOutlinePanel ruleInfo = new JOutlinePanel("Association Rules");
      ruleInfo.setLayout (new GridBagLayout());
      ruleModel = new GenericTableModel(ruleTable.getNumRows(),5,false,columnHeading);
      ruleList = new JTable(ruleModel);
      TableColumnModel colModel = ruleList.getColumnModel();
      colModel.getColumn(0).setPreferredWidth(200);
      colModel.getColumn(1).setPreferredWidth(25);
      colModel.getColumn(2).setPreferredWidth(150);
      colModel.getColumn(3).setPreferredWidth(50);
      colModel.getColumn(4).setPreferredWidth(50);
      JScrollPane tablePane = new JScrollPane(ruleList);
      ruleList.setPreferredScrollableViewportSize (new Dimension(200,350));
      Constrain.setConstraints(ruleInfo, tablePane,
        0,0,1,1,GridBagConstraints.HORIZONTAL, GridBagConstraints.WEST,1,1);

      /* Add the outline panel to displayRulePanel */
      Constrain.setConstraints(displayRulePanel, ruleInfo,
        0,0,3,10,GridBagConstraints.HORIZONTAL,GridBagConstraints.WEST,1,1);
      Constrain.setConstraints(displayRulePanel, printBtn = new JButton ("Print"),
        1,11,1,1,GridBagConstraints.NONE, GridBagConstraints.EAST,1,1);
      printBtn.addActionListener(this);
      Constrain.setConstraints(displayRulePanel, doneBtn = new JButton ("Done"),
        2,11,1,1,GridBagConstraints.NONE, GridBagConstraints.WEST,1,1);
      doneBtn.addActionListener(this);

      setLayout (new BorderLayout());
      add(displayRulePanel, BorderLayout.SOUTH);
    }

    public void actionPerformed(ActionEvent e) {
      Object src = e.getSource();

      if (src == printBtn) {
        writeToFile();
      }
      else if (src == doneBtn) {
        closeIt();
      }
    }
  }
  protected void displayRules() {
    String leftRule;
    String rightRule;
    int tempInt;
    String aLabel;
    // layout of ruleList is: column 1: left handside rule (if rule),
    //                        column 2: symbol "-->",
    //                        column 3: right handside rule (then rule),
    //                        column 4: support,
    //                        column 5: confidence.
    int listSize;
    double aConfidence;
    double minConfidence;
    for (int ruleIdx = 0; ruleIdx < ruleTable.getNumRows(); ruleIdx++) {
      leftRule = NOTHING;
      rightRule = NOTHING;
      int[] head = new int[((int[])ruleTable.getObject(ruleIdx,0)).length];
      head = (int[])ruleTable.getObject(ruleIdx,0);
      int[] body = new int[((int[])ruleTable.getObject(ruleIdx,1)).length];
      body = (int[])ruleTable.getObject(ruleIdx,1);
      // fill in left-hand side rule
      for (int headIdx = 0; headIdx < head.length; headIdx++) {
        tempInt = head[headIdx];
        aLabel = itemLabels.get(tempInt).toString();
        // add a comma between items
        if (headIdx < (head.length-1))
          leftRule = leftRule + aLabel + ",";
        else {
          leftRule = leftRule + aLabel;
          ruleList.setValueAt(leftRule,ruleIdx,0);
        }
      }
      ruleList.setValueAt(" -->",ruleIdx,1);
      for (int bodyIdx = 0; bodyIdx < body.length; bodyIdx++) {
        tempInt = body[bodyIdx];
        aLabel = itemLabels.get(tempInt).toString();
        if (bodyIdx < (body.length-1))
          rightRule = rightRule + aLabel + ",";
        else {
          rightRule = rightRule + aLabel;
          ruleList.setValueAt(rightRule,ruleIdx,2);
        }
      }
      ruleList.setValueAt(Float.toString(ruleTable.getFloat(ruleIdx,2)),ruleIdx,3);
      ruleList.setValueAt(Float.toString(ruleTable.getFloat(ruleIdx,3)),ruleIdx,4);
    }
  }

  protected void closeIt() {
    executionManager.moduleDone(this);
  }

  protected void printItemLabels() {
    System.out.println("item label list in RuleAsscReport: ");
    for (int i = 0; i < itemLabels.size(); i++) {
      System.out.println("item" + i + " is " + itemLabels.get(i).toString() + ", ");
    }
  }

  protected void writeToFile() {
    try {
      String fileName = "ruleAssocation.out";
      String delimiter = "          ";
      String newLine = "\n";

      fw = new FileWriter(fileName);

      String s = "RULE ASSOCIATION: ";
      fw.write(s, 0, s.length());
      fw.write(newLine.toCharArray(), 0, newLine.length());
      fw.write(newLine.toCharArray(), 0, newLine.length());

      // write the actual data
      for(int rowIdx = 0; rowIdx < ruleList.getRowCount(); rowIdx++) {
        for (int colIdx = 0; colIdx < ruleList.getColumnCount(); colIdx++) {
          s = NOTHING;
          if (colIdx == 0) {
            s = "IF (";
            s = s + ruleList.getValueAt(rowIdx, colIdx).toString() + ") ";
          }
          else if (colIdx == 2) {
            s = "THEN (";
            s = s + ruleList.getValueAt(rowIdx, colIdx).toString() + ") ";
          }
          else if (colIdx == 3) {
            s = "with SUPPORT ";
            s = s + ruleList.getValueAt(rowIdx, colIdx).toString();
          }
          else if (colIdx == 4) {
            s = " and CONFIDENCE ";
            s = s + ruleList.getValueAt(rowIdx, colIdx).toString();
          }
          fw.write(s, 0, s.length());
        }
        fw.write(newLine.toCharArray(), 0, newLine.length());
      }
      fw.flush();
      fw.close();
    }
    catch(IOException e) {
      e.printStackTrace();
    }
  }
	/**
	 * Return the human readable name of the module.
	 * @return the human readable name of the module.
	 */
	public String getModuleName() {
		return "RuleAsscReport";
	}

	/**
	 * Return the human readable name of the indexed input.
	 * @param index the index of the input.
	 * @return the human readable name of the indexed input.
	 */
	public String getInputName(int index) {
		switch(index) {
			case 0:
				return "input0";
			case 1:
				return "input1";
			default: return "NO SUCH INPUT!";
		}
	}

	/**
	 * Return the human readable name of the indexed output.
	 * @param index the index of the output.
	 * @return the human readable name of the indexed output.
	 */
	public String getOutputName(int index) {
		switch(index) {
			default: return "NO SUCH OUTPUT!";
		}
	}
}
